services:
  web:
    build: .
    container_name: matriks_web_flask
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # tidak perlu environment FLASK_APP; CMD di Dockerfile sudah mengatur

