version: "3.9"
services:
  web:
    build: .
    container_name: matriks_web_flask
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=web_flask/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
    command: flask run
